name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"

jobs:
  build:
    if: github.repository_owner == 'CommunityRadarGG'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Clean Build
        run: ./gradlew clean build
      - name: Extract Version from Gradle
        run: |
          version=$(./gradlew properties -q | grep "^version:" | awk '{print $2}')
          echo "VERSION=$version" >> $GITHUB_ENV
          echo $version
      - name: Upload Artifact
        if: startsWith(github.event.head_commit.message || '', 'Release')
        uses: actions/upload-artifact@v4
        with:
          name: communityradar-${{ env.VERSION }}
          path: build/libs/*-${{ env.VERSION }}.jar
